### ISSUE TITLE
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | Failed to allocate a 25653658 byte allocation with 15801680 free bytes and 15MB until OOM

### ISSUE THREAD

**Issue by BXFei** [dhhAndroid/RxWebSocket#63]
{"ptid":"22209-1587","stacks":"io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | Failed to allocate a 25653658 byte allocation with 15801680 free bytes and 15MB until OOM\\n\tat io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)\\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)\\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)\\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)\\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)\\n\tat java.lang.Thread.run(Thread.java:760)\\nCaused by: java.lang.OutOfMemoryError: Failed to allocate a 25653658 byte allocation with 15801680 free bytes and 15MB until OOM\\n\tat java.lang.StringFactory.newStringFromBytes(StringFactory.java:176)\\n\tat java.lang.StringFactory.newStringFromBytes(StringFactory.java:207)\\n\tat okio.Buffer.readString(Buffer.java:721)\\n\tat okio.Buffer.readString(Buffer.java:704)\\n\tat okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:208)\\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\\n\tat com.faceball.module_common.retrofit.ResponseInterceptor.intercept(ResponseInterceptor.java:34)\\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\\n\tat com.faceball.module_common.retrofit.CommomInterceptor.intercept(CommomInterceptor.java:147)\\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\\n\tat com.faceball.module_common.retrofit.TokenInterceptor.intercept(TokenInterceptor.java:118)\\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\\n\tat okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)\\n\tat okhttp3.RealCall.execute(RealCall.java:93)\\n\tat retrofit2.OkHttpCall.execute(OkHttpCall.java:180)\\n\tat retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)\\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\\n\tat retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)\\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\\n\tat io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)\\n\tat io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)\\n\tat io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(ObservableFromArray.java:108)\\n\tat io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:37)\\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\\n\tat io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)\\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\\n\tat io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)\\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\\n\tat io.reactivex.internal.schedulers.ScheduledRunnable
2019-06-14 14:47:27.847 22209-22932/com.lvkakeji.faceball E/[RC:L-crash_main_trb-F]: .run(ScheduledRunnable.java:66)\\n\t... 6 more\\n"}
2019-06-14 14:47:27.867 22209-22932/com.lvkakeji.faceball E/RongLog: [ RongExceptionHandler ] uncaughtException
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | Failed to allocate a 25653658 byte allocation with 15801680 free bytes and 15MB until OOM
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 25653658 byte allocation with 15801680 free bytes and 15MB until OOM
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:176)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:207)
        at okio.Buffer.readString(Buffer.java:721)
        at okio.Buffer.readString(Buffer.java:704)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:208)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.faceball.module_common.retrofit.ResponseInterceptor.intercept(ResponseInterceptor.java:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.faceball.module_common.retrofit.CommomInterceptor.intercept(CommomInterceptor.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.faceball.module_common.retrofit.TokenInterceptor.intercept(TokenInterceptor.java:118)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(ObservableFromArray.java:108)
        at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:37)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
2019-06-14 14:47:27.979 1806-1806/? E/Icon: Unable to load resource 0x00000000 from pkg=com.android.systemui
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:201)
        at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
        at android.content.res.Resources.getDrawable(Resources.java:788)
        at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:316)
        at android.graphics.drawable.Icon.loadDrawable(Icon.java:272)
        at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:380)
        at com.android.systemui.statusbar.ExpandedIcon.getDrawable(ExpandedIcon.java:59)
        at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:195)
        at com.android.systemui.statusbar.StatusBarIconView.setIcon(StatusBarIconView.java:142)
        at com.android.systemui.statusbar.StatusBarIconView.updateDarkMode(StatusBarIconView.java:287)
        at com.android.systemui.statusbar.phone.SimpleStatusBar.updateDarkMode(SimpleStatusBar.java:358)
        at com.android.systemui.statusbar.phone.PhoneStatusBar$28.run(PhoneStatusBar.java:4458)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6396)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by dhhAndroid** [comment]
首先这个问题不是RxWebSocket导致的，这个日志上显示是 retrofit 导致的，问题的原因应该是你的某个接口应该是下载大文件的操作，但是没有在接口方法上添加 @Streaming 注解，导致会把文件全部加载到内存，导致OOM。
